repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: ['--ignore-missing-imports', '--no-strict-optional', '--allow-untyped-defs']
        exclude: ^(tests/|examples/)

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.0
    hooks:
      - id: markdownlint-cli2
        args: ['--config', '.markdownlint.json']
